### ISSUE TITLE
No complete for UIKit

### ISSUE THREAD

**Issue by a7med-mahmoud** [swift-server/vscode-swift#129]
No completion for UIKit projects.

**Comment by adam-fowler** [comment]
I believe the LSP server doesn't support iOS frameworks. There maybe some options to enable this. I'll have to ask sourcekit-lsp guys.

**Comment by adam-fowler** [comment]
@ahoppen any reason UIKit doesn't have code completion? I noticed we can get completion for SwiftUI.

Is there a command line parameter you can add to include a framework in code completion?

**Comment by ahoppen** [comment]
The problem is that VSCode doesn’t find the iOS SDK which contains UIKit by default. How would it know that you want to compile for iOS? 😉 
To let it know that you want to build for iOS, figure out the target you are building for and the SDK you are using by building an iOS project in Xcode, opening the build log in Xcode, expanding a “Compile Swift source files” entry and search for the values passed as `-sdk` or `-target`. With these values, add values like the following to “Server Argument” in the VSCode package settings (each line as its own item)
```
-Xswiftc
-sdk
-Xswiftc
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator15.2.sdk
-Xswiftc
-target
-Xswiftc
x86_64-apple-ios15.2-simulator
```

**Comment by adam-fowler** [comment]
thanks @ahoppen
