### ISSUE TITLE
Add placeholder text for protocol requirements 

### ISSUE THREAD

**Issue by nguyenvanzk** [swift-server/vscode-swift#269]
**Is your feature request related to a problem? Please describe.**
When add missing protocol requirements, it will add plain text `<#code#>` instead of placeholder text (can do navigation by tab and delete easily ) to code.

**Describe the solution you'd like**
Add placeholder text like this https://www.youtube.com/watch?v=0XMkg_i5Fqw

**Additional context**
![image](https://user-images.githubusercontent.com/1271860/164700351-430ad1c3-6577-4578-b375-0087eaa2531a.png)

**Comment by adam-fowler** [comment]
Just had a chat with sourcekit-lsp guys and they are going to file a bug internally against sourcekit-lsp to return the correct text for LSP placeholder snippets.

**Comment by adam-fowler** [comment]
This PR in sourcekit-lsp should fix your issue https://github.com/apple/sourcekit-lsp/pull/481. Although I doubt we will see this until Swift 5.7

**Comment by 0xTim** [comment]
We might be able to get it in a monthly Linux release

**Comment by adam-fowler** [comment]
I had a further look into this, and snippets are not supported by textDocument/didChange messages. So unfortunately this does not work. 

There is also the issue that tabbing between placeholders would be awkward because the placeholders will be replaced by code, which could contain tabs. I doubt users will want to move to the next placeholder if they are in the middle of writing a function.

For the immediate future sourcekit-lsp is going to get rid of the `<#code#>` text.

**Comment by adam-fowler** [comment]
This is done, most likely was in 5.7
