### ISSUE TITLE
Locally edited packages in `Packages` folder should be listed

### ISSUE THREAD

**Issue by adam-fowler** [swift-server/vscode-swift#371]
Currently they are not because the workspace.json file doesn't include a path for them. We can work this out though from the `subpath` member ie they are inside the `Packages` folder

**Comment by aelam** [comment]
I don't quite understand the `edited` packages, Could you please share more about it

**Comment by adam-fowler** [comment]
`swift package edit` allows you to edit the code in dependencies. You can either use a local version of the dependency somewhere else on your file system or have it create a copy of the dependency in the `Packages` folder. Currently the extension supports the first case, right click on the extension and chose `use local version`. You can still use the second version but have to type `swift package edit my-dependency` outside of vscode. The problem is when you do this the dependency is removed from the dependency view.

**Comment by aelam** [comment]
Thank s for your answer！

>  You can either use a local version of the dependency somewhere else on your file system or have it create a copy of the dependency in the Packages folder.

Just tried `swift package edit`, and it seems not much difference for `in Packages folder` or not, an alias would be created 

I'm trying to learning the code and fixing it

Is it like this? I tested it with `Packages` folder, it works well

![3333](https://user-images.githubusercontent.com/232337/180657687-8f6da37f-6777-4b88-9687-d90fa54ade58.gif)

When I read the code I got three points that I'd like to share
* it seems that`workspace.json` is all needed for dependency list. 
* `PackageNode` should be prepared before it's used otherwise there would be a lot of conditional checks for paths
* current `type: local, remote, editing` seems to make two types into one type to control 
`local/remote` is a pair
`edited, not_edited` is a pair

#370
