### ISSUE TITLE
Better Handle SourceKit Crashes

### ISSUE THREAD

**Issue by filip-sakel** [swift-server/vscode-swift#395]
**Is your feature request related to a problem? Please describe.**
SourceKit crashes are out of this extension's control but they could be handled better. Xcode, for example, is more robust and even when it crashes I can restart the build without restarting the editor itself. Namely, I get the error that SourceKit crashed more than 5 times in the last minute (or something to that effect), and I don't even have the option of restarting. Furthermore, in Xcode, I can see the diagnostics that occurred right before the crash, but I think that with this extension the diagnostics aren't updated if a crash is detected.

**Describe the solution you'd like**
I would like SourceKit to be automatically restarted after a crash with just a warning message for the user. Further, diagnostics of a SourceKit invocation that crashed should still be emitted similar to Xcode, so that the user has some context for fixing the code that crashes the compiler.

**Describe alternatives you've considered**
The current crash behavior leaves restarting the editor as the only option for the user because there's no option to restart.

**Comment by adam-fowler** [comment]
The restart of the the LSP server is managed by VS Code. The extension plays no part in that. As you'll have seen it tries 5 times and if it crashes 5 times in 3 minutes it doesn't restart again. The dialog shown will also point you to the SourceKit-LSP output window. If you go into the swift extension settings and set `sourcekit-lsp.trace` to verbose, when it crashes you will see in the SourceKit-LSP output window a complete list of the requests and their related responses made to the LSP server. I think it acceptable to assume that one of those requests that hasn't received a response will have caused the crash.

Given the VS Code swift extension has no control over the restart behaviour, if you want a more refined response you should add an issue to the vscode repo https://github.com/microsoft/vscode.

As an aside you don't need to restart VS Code. You can run the command `Developer: Reload Window`

**Comment by filip-sakel** [comment]
Thanks for the quick reply and the reload-window command. I think we’re stuck in a weird situation because it makes sense why VS Code would shut off SourceKit LSP after enough failures, but at the same time the swift compiler is quite crashy (at least with all the new generics/existential features). I wonder if there’s an in between solution where VS Code could let extensions define how many failures to tolerate. Or perhaps we could make it such that a compiler crash produces an error diagnostic instead of also crashing SourceKit LSP.

**Comment by adam-fowler** [comment]
I'm not sure increasing retries helps. Given the same file is being displayed and it'll just crash again immediately. Anyway the extension doesn't have control over that. Asking the vscode language extension to blacklist certain files because they keep crashing the LSP server might be an improvement. Although I doubt it will be a priority for them. Their response will be fix your LSP server.

I'm not sure it is compiler crashes that is bringing down SourceKit-LSP. You could ask the SourceKit-LSP guys if that could be the case. The one's I've seen are actually crashes in SourceKit-LSP. Again though this isn't something the extension has control over. The one I saw seemed to be related to InlayHints. And it was fixed in the next nightly I downloaded. 

Most solutions don't involve the extension. The extension defines how to start the LSP server and then it basically hands off the handling of the LSP server process to VS Code.

**Comment by filip-sakel** [comment]
Alright, I’ll look at the logs if I get another crash to determine the cause and report back to SourceKit LSP if I have any problems.
