### ISSUE TITLE
Run option similar to auto-build option.

### ISSUE THREAD

**Issue by mikebronner** [swift-server/vscode-swift#410]
**Describe the solution you'd like**
Similar to the Background Compilation option, it would be awesome to have an option to run in the background whenever a file is saved. This would be tremendously helpful in streamlining the development flow when working with Swift Vapor in VSCode alongside the front-end stack. The idea would be that it would execute `swift run` on the vapor project, and thereby always keep the website running with the latest changes, without me having to manually restart the process after each change, wait for it to finish, and then refresh the website.

As a bonus, it would be awesome if there would be a way to hot-refresh the browser at the same time. Perhaps allowing us to specify a command to execute once the run command was triggered would help in that regard, not exactly sure what the options are there, as it seems very specific to Vapor.

I was able to get a post-build script configured in xcode that does what I want:
```
#!/bin/bash
kill $(lsof -t -i:8080)
cd ${WORKSPACE_PATH}/../../..
/opt/homebrew/bin/vapor run
```

This will kill any previously running vapor server, switch to the project folder, and restart the vapor web server. Unfortunately it seems that the XCode Scheme that contains the post-build script is not executed. Is there way to provide arguments to the Swfit Build Arguments settings that could either point to a script in the project, or the xcode scheme file?

**Comment by adam-fowler** [comment]
At the moment you can add pre-build tasks (by editing the build task), but post-build tasks aren't possible. I had a quick look into whether you could edit the build task so it ran `swift run` instead of `swift build` which is perfectly possible, but it means you have a task running all the time and no other task would run for that workspace folder. I run `swift` tasks serially to avoid multiple builds, resolve, updates running on the same folder at the same time. 

I'll do some more investigation, but in the end I could add post build tasks.

Out of interest in Xcode with the above post-build script if you run the project using `Cmd+R` does this post-build script interfere with the running of your project in the debugger.

**Comment by stevapple** [comment]
Can we track `swift run` state as a language status item? This looks more Xcode-like and easier to control.

**Comment by adam-fowler** [comment]
With the release of 1.5 the default build task, will be used for background compilation. So you can create your own build task  which calls `kill $(lsof -t -i:8080); swift run` or something similar, and then set this to be the default build task.
