### ISSUE TITLE
how to disable codelldb?

### ISSUE THREAD

**Issue by garymaxallen** [swift-server/vscode-swift#504]
**Is your feature request related to a problem? Please describe.**
yes, codelldb keeps making my vscode crash. I don't need the debug feature. I just use vscode to edit code.

**Describe the solution you'd like**
I want an option to disable codelldb, I don't think making vscode-swift dependent on codelldb is a good idea. That's not decoupling.

**Comment by 0xTim** [comment]
What crashes are you seeing? 

VSCode Swift must absolutely depend upon CodeLLDB since it's the debugger we rely on. Having an extension that provides a seamless experience for Swift, including setting up a debugger is the main point. (That's not to say we couldn't add a flag to disable it but it must depend on it)

**Comment by adam-fowler** [comment]
Could you provide platform and version details alongside any details about the crashes you are experiencing. Thank you

**Comment by garymaxallen** [comment]
I'm sorry I maybe too paranoid about CodeLLDB, it maybe crashed a few times or not. 
But that's not the point. 
I just want to disable the CodeLLDB extension but can't because it says swift depends on it. That makes me crazy. I don't need it.
Sorry about my pranoia and craziness. But I still think forcefully combine these two independent extensions together isn't a good idea.

**Comment by adam-fowler** [comment]
I had a look at if I could do a softer dependency. ie I would remove the hard dependency and manage this within the extension by showing dialog and suggest people download vscode-lldb if they want to use the debugger. 

It has to be easy to install CodeLLDB from this dialog though otherwise we will get loads of people complaining they can't debug their apps. Unfortunately VSCode gives me no method to install an extension, or even link to an extension in the app. I would need at least one of these if I was to break the dependency between vscode-swift and vscode-lldb. Otherwise I am asking users to go search for a debugger extension they most likely won't know about. This would be poor UX design.

**Comment by garymaxallen** [comment]
It's this problem that I encountered.
It occured occasionally. very disturbing.

See the bottom, It says Acquiring CodeLLDB platform package. 
If it's acquiring slow, it will be there permanently, you can't cancel it. 

<img width="598" alt="image" src="https://user-images.githubusercontent.com/10022333/225679825-16c74194-9902-41d1-bdfd-f5e956741125.png">

**Comment by adam-fowler** [comment]
Yes you will see that every time you create a new container. I have no control over that dialog. It is VSCode downloading the platform specific requirements for CodeLLDB.
