### ISSUE TITLE
`Cannot parse swift target info output` for Swift 5.1

### ISSUE THREAD

**Issue by sevetseh28** [swift-server/vscode-swift#572]
Hi! I tried installing the extension in a devcontainer using Swift 5.1 but got

`Cannot parse swift target info output`

Checking the source code I saw this error originates here:
https://github.com/swift-server/vscode-swift/blob/3f9563e75c7349fd59b85a5948e9bcc11d83d58b/src/toolchain/toolchain.ts#L447

so that means it will try running `swift -print-target-info` and it'll fail for Swift 5.1. The code should fall back to using `swift --version` which in my case outputs to:
```
Swift version 5.1.5 (swift-5.1.5-RELEASE)
Target: x86_64-unknown-linux-gnu
```

Reading the source code it seems an exception is being raised before running this command as the regex should correctly capture the first line.

I will try to find time to fix this but in the meantime I wanted to leave it reported here and maybe someone can catch it sooner.

Thanks!

**Comment by adam-fowler** [comment]
Hi, when we started developing the extension Swift 5.5 was already out. There are some features of the extension that just won't be available for versions earlier than 5.4 because features of SwiftPM we depend on do not exist in those releases. 

I did not realise the version check was completely failing when target info was not available. Is 5.1 something you require or is this issue just something to note?
