### ISSUE TITLE
[Windows] No program output when run using launch config

### ISSUE THREAD

**Issue by tomwyr** [swift-server/vscode-swift#700]
**Describe the bug**
I have setup a simple project created using `swift package init --type executable` with the code visible on the recording. When I launch the code using one of the generated debug/release launch configs, the compiled code executes without any output.

**Expected behavior**
I can see the output of my program either in the internal or external terminal windows.

https://github.com/swift-server/vscode-swift/assets/9600796/77e1a91d-094c-4a27-ade8-cf08fe44739a

**Environment**
 - OS: Windows 11 (10.0.22631 Build 22631)
 - Swift version 5.9.2
 - Visual Studio Code version: 1.86.2
 - vscode-swift version: 1.8.0

**Comment by adam-fowler** [comment]
This is an issue with the Windows version of LLDB that comes with the Swift installation.
This issue can be found here #309 
One thing that has changed since then though is the availability of the llvm lldb debug adapter in the Swift installation. Can you see if you still get this if you go to the Settings and select `Swift › Debugger: Use Debug Adapter From Toolchain`

**Comment by tomwyr** [comment]
Thanks for the suggestion @adam-fowler I tried changing the adapter and the outcome is that running the code spawns a terminal window without producing any output. The debug session keeps running until I close the window or stop it from vscode.

**Comment by adam-fowler** [comment]
I'm going to close this is favour of 309 as it is a duplicate. I've tried to resurrect the conversation on that issue as well
