### ISSUE TITLE
Use `lldb-dap` instead of `CodeLLDB` for debugging

### ISSUE THREAD

**Issue by ahoppen** [swift-server/vscode-swift#749]
If the Swift toolchain includes `lldb-dap` (which recent Swift development snapshots for 6.0 and `main` do), I think we should use that to debug an executable instead of relying on `CodeLLDB`.

**Comment by adam-fowler** [comment]
`lldb-dap` is not in the Linux toolchain. Anyway you can already use it by selecting the option `Swift > Debugger: Use debug adapter from toochain`. Temporarily in a release version of the extension you also need to set the path to the debug adapter as well because the current release uses the old debug adapter name `lldb-vscode`.

**Comment by JDevlieghere** [comment]
@adam-fowler with https://github.com/llvm/llvm-project/pull/88482 (and the corresponding cherry-pick to the Swift branches), do you think we can make that the default (and have a fallback for the old name in older releases)?

**Comment by adam-fowler** [comment]
There is a change, not yet released that uses lldb-dap if the Swift version is 6 or above.

**Comment by adam-fowler** [comment]
@JDevlieghere v1.9 which has just been released uses `lldb-dap` for swift 6 builds.

**Comment by felixf4xu** [comment]
I checked the setting for v1.11.1, the setting is there, but default value is off (not checked). If it can fallback to CodeLLDB when lldb-dap is not available, I think the setting should be default to ON.
